### ISSUE TITLE
Mind to add CONTRIBUTING.md?

### ISSUE THREAD

**Issue by S-aiueo32** [romesco/hydra-lightning#11]
Hi,

I would like to contribute to this project and hope that more people will participate. However, this project does not have a contribution guide or roadmap, so it's hard to know what and how to help. For example, it is not clear whether the dataclass needs to be generated by configen or if it can be added manually.

Why not add CONTRIBUTING.md to the repository as a way to expand the community?

In my opinion, I hope the project will be merged with PyTorch and Lightning, as Hydra is very useful and dataclass is a very versatile interface.
Thanks!

**Comment by romesco** [comment]
Absolutely. We should work on this together! It's an excellent idea! I'll set up a CONTRIBUTING as well as a roadmap.

Its on my near-term TODO to get meaningful CI with proper tests (just like I set up on the hydra-torch repo).

@S-aiueo32 Check back in a day or so and I'll write down what we need to do to move forward!

**Comment by romesco** [comment]
@S-aiueo32

I've updated [Contributing.MD](https://github.com/romesco/hydra-lightning/blob/main/CONTRIBUTING.md) again with a detailed outline of how to set up a dev environment in line with CI.

CI now also integrates testing and requires 100% test coverage before merge!

Feel free to ping me on the [hydra chat](https://hydra-framework.zulipchat.com/#) @ rosario if you need any additional guidance in terms of contributing! 🤠  Would love your help!
